name: uni_tool
description: uni tool for UNI'S ON AIR

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.10.0
  flutter_riverpod: ^1.0.1
  keyboard_actions: ^4.0.1
  convex_bottom_bar: ^3.0.0
  flutter_switch: ^0.3.2
  package_info: ^2.0.2
  url_launcher: ^6.1.5
  flutter_native_splash: ^2.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/uoa_icon.png'

flutter_native_splash:
  image: 'assets/images/splash_icon.png'
  color: 'FFFFFF'
